### ISSUE TITLE
Default Password for OpenBMC

### ISSUE THREAD

**Issue by jyasir** [openbmc/meta-hpe#1]
What are the default credentials for OpenBMC implementation on DL325Gen10p?

**Comment by vejmarie** [comment]
Hi, it is root/0penBmc (first letter is number zero not o)

**Comment by jyasir** [comment]
thanks and its Username "Administrator" or something else?

**Comment by jyasir** [comment]
Thanks.

**Comment by vejmarie** [comment]
you are welcome. Feel free to join HPE OpenBMC discord channel if you want to.

**Comment by jyasir** [comment]
HPE veteran here, there is always a place for HPE servers in my heart ;)

**Comment by vejmarie** [comment]
> HPE veteran here, there is always a place for HPE servers in my heart ;)

Cool. Ping me if you have question regarding OpenBMC on HPE. I am part of the team who works on it.

**Comment by jyasir** [comment]
Cool, we just got one system from HPE and the default as well as the one on the box sticker is not working so we will be reaching out to HPE regarding correct credentials.

**Comment by vejmarie** [comment]
Did it came with OpenBMC pre-loaded ? If yes it is probably coming from my team
